@EmployeeAdminPortal_HostAddress = https://localhost:7247

GET {{EmployeeAdminPortal_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{EmployeeAdminPortal_HostAddress}}/api/employees

###
